name: chewie_vlc
description: Based on Chewie from http://github.com/fluttercommunity/chewie, it uses flutter-vlc-player instead of video-player
version: 1.7.5
homepage: http://github.com/amoinier/chewie_vlc

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_vlc_player: ^7.4.1
  provider: ^6.0.5
  wakelock_plus: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
